baseurl = "https://itzsaga.github.io/"
languageCode = "en-us"
title = "My Flatiron Journey"
# Define how many pages appear per site
paginate = 10
# Enable comments powered by Disqus by entering your disqus shortname
disqusShortname = "my-flatiron-journey"
# Enable gogle analytics by entering your tracking code
googleAnalytics = ""
theme = "hugo-minimalist-theme"
# Remove this line if you use this theme for a real website.
# It allows you to preview the theme within the exampleSite folder
# with the hugo server command
# themesDir = "../.."

[params]
    site_author = "Seth Alexander"
    site_description = "My journey to becoming a web developer by means of the Flatiron Online Web Development boot camp."
    location = "Nashville"
    # Link custom assets relative to /static
    avatar = "img/profile-image.png"
    header_background = "img/desk.jpg"
    header_title = "My Flatiron Journey"
    copyright = "Powered by [Hugo](http://gohugo.io)."
    custom_css = []
    custom_js  = []

    # Enable gogle analytics by entering your tracking code
    google_analytics = ""

[social]
    # Add your social network accounts to the profile section on the left
    # by entering your username. The links to your account will be
    # create automatically.
    twitter   = "itzsaga"
    facebook  = ""
    linkedin  = "sethalexander"
    behance   = ""
    dribbble  = ""
    instagram = "sethaalexander"
    github    = "itzsaga"
    gplus     = ""
